export const ROUTES = {
  ROOT: '/',
  UPLOADS: '/uploads',
  API: {
    CUSTOMERS: '/api/customers',
    VENDORS: '/api/vendors',
    PRODUCTS: '/api/products',
    ORDERS: '/api/orders',
    ORDER_ITEMS: '/api/order-items',
    NOTIFICATIONS: '/api/notifications',
    ADMIN: '/api/admin',
  },
  CUSTOMERS: {
    LOGIN: '/login',
    REGISTER: '/register',
    BASE: '/',
    BY_ID: '/:customerId',
    PROFILE_PHOTO: '/:customerId/profile-photo',
  },
  VENDORS: {
    LOGIN: '/login',
    BASE: '/',
    BY_ID: '/:id',
    EMAIL: '/email/:email',
    PHONE: '/phone/:phone',
    TYPE: '/type/:type',
    PROFILE_PHOTO: '/:id/profile-photo',
  },
  PRODUCTS: {
    BASE: '/',
    SEARCH: '/search',
    BY_SELLER: '/seller/:sellerId',
    BY_ID: '/:id',
    VARIANTS: '/:productId/variants',
    VARIANT_BY_ID: '/:productId/variants/:variantId',
  },
  ORDERS: {
    BASE: '/',
    PAST_ALL: '/past/all',
    BY_ID: '/:orderId',
    BY_CUSTOMER: '/customer/:customerId',
    PAST_BY_CUSTOMER: '/customer/:customerId/past',
    BY_VENDOR: '/vendor/:vendorId',
    STATUS: '/:orderId/status',
    PAYMENT_STATUS: '/:orderId/payment-status',
  },
  ORDER_ITEMS: {
    BASE: '/',
    BY_ID: '/:orderItemId',
    BY_ORDER: '/order/:orderId',
    BY_PRODUCT: '/product/:productId',
  },
  NOTIFICATIONS: {
    BASE: '/',
    TYPE: '/type/:type',
    PRIORITY: '/priority/:priority',
    ORDER: '/order/:orderId',
    PRODUCT: '/product/:productId',
    BY_ID: '/:notificationId',
    CUSTOMER: '/customer/:customerId',
    CUSTOMER_UNREAD: '/customer/:customerId/unread',
    CUSTOMER_UNREAD_COUNT: '/customer/:customerId/unread-count',
    VENDOR: '/vendor/:vendorId',
    VENDOR_UNREAD: '/vendor/:vendorId/unread',
    VENDOR_UNREAD_COUNT: '/vendor/:vendorId/unread-count',
    READ_MULTIPLE: '/read/multiple',
    DELETE_MULTIPLE: '/delete/multiple',
  },
  ADMIN: {
    BASE: '/',
    AUTH_LOGIN: '/auth/login',
    AUTH_ME: '/auth/me',
    DASHBOARD_SUMMARY: '/dashboard/summary',
    CONFIGURATION: '/configuration',
    CUSTOMERS: '/customers',
    CUSTOMER_BY_ID: '/customers/:customerId',
    VENDORS: '/vendors',
    VENDOR_BY_ID: '/vendors/:vendorId',
    PRODUCTS: '/products',
    PRODUCT_BY_ID: '/products/:productId',
    ORDERS: '/orders',
    ORDER_BY_ID: '/orders/:orderId',
    NOTIFICATIONS: '/notifications',
  },
};